-- Migration 0022: Endpoint/schema compatibility hardening
-- Keeps existing rows intact while making active API write/display paths
-- compatible with the current application contracts.

-- ---------------------------------------------------------------------------
-- pending_admissions: active admission workflow typed columns + raw JSON blobs
-- ---------------------------------------------------------------------------
ALTER TABLE care.pending_admissions
  ADD COLUMN IF NOT EXISTS preferred_name TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS address_line1 TEXT,
  ADD COLUMN IF NOT EXISTS address_line2 TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS language_preference TEXT,
  ADD COLUMN IF NOT EXISTS tribal_affiliation TEXT,
  ADD COLUMN IF NOT EXISTS spiritual_religious TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship TEXT,
  ADD COLUMN IF NOT EXISTS primary_diagnosis TEXT,
  ADD COLUMN IF NOT EXISTS has_guardian BOOLEAN,
  ADD COLUMN IF NOT EXISTS guardian_representative TEXT,
  ADD COLUMN IF NOT EXISTS medicaid_id TEXT,
  ADD COLUMN IF NOT EXISTS ssn_last4 TEXT,
  ADD COLUMN IF NOT EXISTS substance_use_flag BOOLEAN,
  ADD COLUMN IF NOT EXISTS legal_risk_flag BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_advance_directive BOOLEAN,
  ADD COLUMN IF NOT EXISTS healthcare_agent_relationship TEXT,
  ADD COLUMN IF NOT EXISTS witness1_name TEXT,
  ADD COLUMN IF NOT EXISTS witness1_signature TEXT,
  ADD COLUMN IF NOT EXISTS witness1_date DATE,
  ADD COLUMN IF NOT EXISTS witness2_name TEXT,
  ADD COLUMN IF NOT EXISTS witness2_signature TEXT,
  ADD COLUMN IF NOT EXISTS witness2_date DATE,
  ADD COLUMN IF NOT EXISTS pre_screening_data JSONB,
  ADD COLUMN IF NOT EXISTS nursing_assessment_data JSONB,
  ADD COLUMN IF NOT EXISTS advance_directive_data JSONB,
  ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_pending_admissions_submitted
  ON care.pending_admissions(tenant_id, submitted_at DESC)
  WHERE submitted_at IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Legacy direct pre-admission endpoint columns
-- ---------------------------------------------------------------------------
ALTER TABLE care.pre_admission_screenings
  ADD COLUMN IF NOT EXISTS referring_agency_name TEXT,
  ADD COLUMN IF NOT EXISTS referral_date_admission DATE,
  ADD COLUMN IF NOT EXISTS contact_person_name TEXT,
  ADD COLUMN IF NOT EXISTS contact_phone_number VARCHAR(30),
  ADD COLUMN IF NOT EXISTS contact_email_address VARCHAR(200),
  ADD COLUMN IF NOT EXISTS ssn_number TEXT,
  ADD COLUMN IF NOT EXISTS ohp_id_number TEXT,
  ADD COLUMN IF NOT EXISTS other_insurance_carrier TEXT,
  ADD COLUMN IF NOT EXISTS other_insurance_id TEXT,
  ADD COLUMN IF NOT EXISTS county_of_residence_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS presenting_problem_details TEXT,
  ADD COLUMN IF NOT EXISTS primary_diagnosis_code TEXT,
  ADD COLUMN IF NOT EXISTS diagnosis_date_screening DATE,
  ADD COLUMN IF NOT EXISTS secondary_diagnoses_screening TEXT,
  ADD COLUMN IF NOT EXISTS psych_meds_list JSONB,
  ADD COLUMN IF NOT EXISTS psych_hospitalization_hx_screening VARCHAR(10),
  ADD COLUMN IF NOT EXISTS psych_hospitalization_date DATE,
  ADD COLUMN IF NOT EXISTS psych_hospitalization_reason_screening TEXT,
  ADD COLUMN IF NOT EXISTS therapist_name_screening TEXT,
  ADD COLUMN IF NOT EXISTS therapist_phone_screening VARCHAR(30),
  ADD COLUMN IF NOT EXISTS psychiatrist_name_screening TEXT,
  ADD COLUMN IF NOT EXISTS psychiatrist_phone_screening VARCHAR(30),
  ADD COLUMN IF NOT EXISTS case_manager_name_screening TEXT,
  ADD COLUMN IF NOT EXISTS case_manager_phone_screening VARCHAR(30),
  ADD COLUMN IF NOT EXISTS pcp_name_screening TEXT,
  ADD COLUMN IF NOT EXISTS pcp_phone_screening VARCHAR(30),
  ADD COLUMN IF NOT EXISTS pcp_fax_screening VARCHAR(30),
  ADD COLUMN IF NOT EXISTS medical_diagnoses_screening TEXT,
  ADD COLUMN IF NOT EXISTS non_psych_meds_list JSONB,
  ADD COLUMN IF NOT EXISTS mobility_status_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS assistive_device_type TEXT,
  ADD COLUMN IF NOT EXISTS adl_assistance_notes TEXT,
  ADD COLUMN IF NOT EXISTS tb_test_result_screening VARCHAR(50),
  ADD COLUMN IF NOT EXISTS tb_test_date_screening DATE,
  ADD COLUMN IF NOT EXISTS covid_vaccination_status_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS other_communicable_disease_status TEXT,
  ADD COLUMN IF NOT EXISTS primary_substance_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS secondary_substances_screening TEXT,
  ADD COLUMN IF NOT EXISTS last_use_date_screening DATE,
  ADD COLUMN IF NOT EXISTS route_of_use_screening VARCHAR(50),
  ADD COLUMN IF NOT EXISTS withdrawal_history_screening VARCHAR(10),
  ADD COLUMN IF NOT EXISTS withdrawal_details_screening TEXT,
  ADD COLUMN IF NOT EXISTS previous_treatment_episodes TEXT,
  ADD COLUMN IF NOT EXISTS primary_income_source_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS income_details_screening TEXT,
  ADD COLUMN IF NOT EXISTS legal_status_screening VARCHAR(100),
  ADD COLUMN IF NOT EXISTS probation_officer_name TEXT,
  ADD COLUMN IF NOT EXISTS probation_officer_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS legal_conditions_supervision TEXT,
  ADD COLUMN IF NOT EXISTS willing_discuss_trauma VARCHAR(50),
  ADD COLUMN IF NOT EXISTS client_strengths_interests TEXT,
  ADD COLUMN IF NOT EXISTS abh_home_assessed VARCHAR(50),
  ADD COLUMN IF NOT EXISTS lmha_connected_screening VARCHAR(10),
  ADD COLUMN IF NOT EXISTS lmha_contact_info TEXT,
  ADD COLUMN IF NOT EXISTS waitlist_other_services_screening TEXT,
  ADD COLUMN IF NOT EXISTS level_of_care_needs_screening TEXT[],
  ADD COLUMN IF NOT EXISTS level_of_care_other_needs TEXT,
  ADD COLUMN IF NOT EXISTS strengths_summary_assessor TEXT,
  ADD COLUMN IF NOT EXISTS barriers_to_placement_screening TEXT,
  ADD COLUMN IF NOT EXISTS assessor_recommendation_screening TEXT,
  ADD COLUMN IF NOT EXISTS screening_outcome_screening VARCHAR(50),
  ADD COLUMN IF NOT EXISTS conditions_prior_admission_screening TEXT,
  ADD COLUMN IF NOT EXISTS assessor_name_screening TEXT,
  ADD COLUMN IF NOT EXISTS assessor_title_screening TEXT,
  ADD COLUMN IF NOT EXISTS assessor_signature_screening TEXT,
  ADD COLUMN IF NOT EXISTS assessor_date_screening DATE,
  ADD COLUMN IF NOT EXISTS local_crisis_line TEXT,
  ADD COLUMN IF NOT EXISTS step_1_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_2_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_3_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_4_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_5_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_6_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS submitted_by UUID REFERENCES ref.staff(id);

-- ---------------------------------------------------------------------------
-- Legacy direct nursing endpoint columns
-- ---------------------------------------------------------------------------
ALTER TABLE care.nursing_admissions
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE,
  ADD COLUMN IF NOT EXISTS age SMALLINT,
  ADD COLUMN IF NOT EXISTS gender VARCHAR(50),
  ADD COLUMN IF NOT EXISTS preferred_name TEXT,
  ADD COLUMN IF NOT EXISTS pronouns VARCHAR(50),
  ADD COLUMN IF NOT EXISTS language_preference VARCHAR(50),
  ADD COLUMN IF NOT EXISTS interpreter_needed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ethnicity VARCHAR(50),
  ADD COLUMN IF NOT EXISTS race TEXT[],
  ADD COLUMN IF NOT EXISTS arrival_method VARCHAR(50),
  ADD COLUMN IF NOT EXISTS info_source TEXT[],
  ADD COLUMN IF NOT EXISTS spiritual_practices VARCHAR(10),
  ADD COLUMN IF NOT EXISTS spiritual_details TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship VARCHAR(50),
  ADD COLUMN IF NOT EXISTS reason_for_admission TEXT,
  ADD COLUMN IF NOT EXISTS present_illness_history TEXT,
  ADD COLUMN IF NOT EXISTS orientation_items TEXT[],
  ADD COLUMN IF NOT EXISTS temperature VARCHAR(20),
  ADD COLUMN IF NOT EXISTS height VARCHAR(20),
  ADD COLUMN IF NOT EXISTS weight_actual VARCHAR(20),
  ADD COLUMN IF NOT EXISTS weight_stated VARCHAR(20),
  ADD COLUMN IF NOT EXISTS no_known_allergies VARCHAR(10),
  ADD COLUMN IF NOT EXISTS allergy_medication TEXT,
  ADD COLUMN IF NOT EXISTS allergy_food TEXT,
  ADD COLUMN IF NOT EXISTS allergy_environmental TEXT,
  ADD COLUMN IF NOT EXISTS allergy_latex TEXT,
  ADD COLUMN IF NOT EXISTS allergy_other TEXT,
  ADD COLUMN IF NOT EXISTS scalp_inspected VARCHAR(10),
  ADD COLUMN IF NOT EXISTS scalp_not_inspected_reason TEXT,
  ADD COLUMN IF NOT EXISTS skin_findings TEXT[],
  ADD COLUMN IF NOT EXISTS skin_findings_other TEXT,
  ADD COLUMN IF NOT EXISTS skin_staff_1 TEXT,
  ADD COLUMN IF NOT EXISTS neuro TEXT[],
  ADD COLUMN IF NOT EXISTS neuro_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cardio TEXT[],
  ADD COLUMN IF NOT EXISTS cardio_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS respiratory TEXT[],
  ADD COLUMN IF NOT EXISTS respiratory_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS gi TEXT[],
  ADD COLUMN IF NOT EXISTS gi_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS renal TEXT[],
  ADD COLUMN IF NOT EXISTS renal_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS musculo TEXT[],
  ADD COLUMN IF NOT EXISTS musculo_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS eent TEXT[],
  ADD COLUMN IF NOT EXISTS eent_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS skin TEXT[],
  ADD COLUMN IF NOT EXISTS skin_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tb_symptoms TEXT[],
  ADD COLUMN IF NOT EXISTS tb_symptoms_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hepatitis_symptoms TEXT[],
  ADD COLUMN IF NOT EXISTS hepatitis_symptoms_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hiv_symptoms TEXT[],
  ADD COLUMN IF NOT EXISTS hiv_symptoms_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS flu_symptoms TEXT[],
  ADD COLUMN IF NOT EXISTS flu_symptoms_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mrsa_symptoms TEXT[],
  ADD COLUMN IF NOT EXISTS mrsa_symptoms_denies BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS flu_vax_consent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS med_surg_history TEXT,
  ADD COLUMN IF NOT EXISTS repro_female TEXT[],
  ADD COLUMN IF NOT EXISTS repro_male TEXT[],
  ADD COLUMN IF NOT EXISTS pain_present VARCHAR(10),
  ADD COLUMN IF NOT EXISTS pain_scale SMALLINT,
  ADD COLUMN IF NOT EXISTS pain_comfort_goal SMALLINT,
  ADD COLUMN IF NOT EXISTS pain_onset VARCHAR(20),
  ADD COLUMN IF NOT EXISTS pain_duration VARCHAR(20),
  ADD COLUMN IF NOT EXISTS pain_description TEXT[],
  ADD COLUMN IF NOT EXISTS pain_relief TEXT[],
  ADD COLUMN IF NOT EXISTS sleep_hours NUMERIC(3,1),
  ADD COLUMN IF NOT EXISTS sleep_medication VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sleep_medication_detail TEXT,
  ADD COLUMN IF NOT EXISTS sleep_pattern TEXT[],
  ADD COLUMN IF NOT EXISTS sleep_apnea VARCHAR(10),
  ADD COLUMN IF NOT EXISTS cpap_use VARCHAR(10),
  ADD COLUMN IF NOT EXISTS cpap_brought VARCHAR(10),
  ADD COLUMN IF NOT EXISTS tobacco_status VARCHAR(50),
  ADD COLUMN IF NOT EXISTS tobacco_type TEXT[],
  ADD COLUMN IF NOT EXISTS special_diet TEXT,
  ADD COLUMN IF NOT EXISTS food_allergies TEXT,
  ADD COLUMN IF NOT EXISTS last_meal TEXT,
  ADD COLUMN IF NOT EXISTS nutrition_concerns TEXT[],
  ADD COLUMN IF NOT EXISTS adl_ambulation VARCHAR(50),
  ADD COLUMN IF NOT EXISTS adl_transferring VARCHAR(50),
  ADD COLUMN IF NOT EXISTS assist_devices TEXT[],
  ADD COLUMN IF NOT EXISTS can_read VARCHAR(10),
  ADD COLUMN IF NOT EXISTS can_write VARCHAR(10),
  ADD COLUMN IF NOT EXISTS learning_challenges TEXT[],
  ADD COLUMN IF NOT EXISTS learning_preferences TEXT[],
  ADD COLUMN IF NOT EXISTS audit_c1 VARCHAR(5),
  ADD COLUMN IF NOT EXISTS audit_c2 VARCHAR(5),
  ADD COLUMN IF NOT EXISTS audit_c3 VARCHAR(5),
  ADD COLUMN IF NOT EXISTS substance_use_12mo VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sobriety_period TEXT,
  ADD COLUMN IF NOT EXISTS family_sa_hx VARCHAR(10),
  ADD COLUMN IF NOT EXISTS self_help_groups TEXT[],
  ADD COLUMN IF NOT EXISTS treatment_reason TEXT,
  ADD COLUMN IF NOT EXISTS use_triggers TEXT,
  ADD COLUMN IF NOT EXISTS use_consequences TEXT[],
  ADD COLUMN IF NOT EXISTS alcohol_detox_hx VARCHAR(10),
  ADD COLUMN IF NOT EXISTS alcohol_seizure_hx VARCHAR(10),
  ADD COLUMN IF NOT EXISTS loc VARCHAR(50),
  ADD COLUMN IF NOT EXISTS orientation TEXT[],
  ADD COLUMN IF NOT EXISTS attention TEXT[],
  ADD COLUMN IF NOT EXISTS appearance TEXT[],
  ADD COLUMN IF NOT EXISTS behavior TEXT[],
  ADD COLUMN IF NOT EXISTS interactions TEXT[],
  ADD COLUMN IF NOT EXISTS psychomotor TEXT[],
  ADD COLUMN IF NOT EXISTS speech TEXT[],
  ADD COLUMN IF NOT EXISTS mood TEXT[],
  ADD COLUMN IF NOT EXISTS affect TEXT[],
  ADD COLUMN IF NOT EXISTS thought_process TEXT[],
  ADD COLUMN IF NOT EXISTS thought_content TEXT[],
  ADD COLUMN IF NOT EXISTS hallucinations TEXT[],
  ADD COLUMN IF NOT EXISTS insight VARCHAR(50),
  ADD COLUMN IF NOT EXISTS judgment VARCHAR(50),
  ADD COLUMN IF NOT EXISTS mse_comments TEXT,
  ADD COLUMN IF NOT EXISTS elopement_risk TEXT[],
  ADD COLUMN IF NOT EXISTS violence_hcw VARCHAR(50),
  ADD COLUMN IF NOT EXISTS violence_history VARCHAR(50),
  ADD COLUMN IF NOT EXISTS violence_risk_factors TEXT[],
  ADD COLUMN IF NOT EXISTS violence_comments TEXT,
  ADD COLUMN IF NOT EXISTS trauma_history TEXT[],
  ADD COLUMN IF NOT EXISTS sexual_victimization_6mo VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sexual_victimization_lifetime VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sexual_victimization_indicators TEXT[],
  ADD COLUMN IF NOT EXISTS sexual_aggression_6mo VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sexual_aggression_lifetime VARCHAR(10),
  ADD COLUMN IF NOT EXISTS sexual_aggression_indicators TEXT[],
  ADD COLUMN IF NOT EXISTS restraint_sexual_abuse VARCHAR(10),
  ADD COLUMN IF NOT EXISTS restraint_physical_abuse VARCHAR(10),
  ADD COLUMN IF NOT EXISTS restraint_medical_issues VARCHAR(10),
  ADD COLUMN IF NOT EXISTS restraint_notify TEXT,
  ADD COLUMN IF NOT EXISTS suicide_protective TEXT[],
  ADD COLUMN IF NOT EXISTS suicide_risk TEXT[],
  ADD COLUMN IF NOT EXISTS csrs1 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS csrs2 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS csrs3 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS csrs4 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS csrs5 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS csrs6 VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_suicide VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_fall VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_assault VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_seizure VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_medical VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_elopement VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_sexual_v VARCHAR(10),
  ADD COLUMN IF NOT EXISTS summary_risk_sexual_a VARCHAR(10),
  ADD COLUMN IF NOT EXISTS observation_level VARCHAR(50),
  ADD COLUMN IF NOT EXISTS narrative_summary TEXT,
  ADD COLUMN IF NOT EXISTS rn_name TEXT,
  ADD COLUMN IF NOT EXISTS rn_signed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS staff_number TEXT,
  ADD COLUMN IF NOT EXISTS rn_signature TEXT,
  ADD COLUMN IF NOT EXISTS step_1_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_2_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_3_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_4_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_5_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_6_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_7_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_8_completed BOOLEAN DEFAULT FALSE;

-- ---------------------------------------------------------------------------
-- Legacy direct advance-directive endpoint columns
-- ---------------------------------------------------------------------------
ALTER TABLE care.advance_directives
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS clarification_notes TEXT,
  ADD COLUMN IF NOT EXISTS has_agent VARCHAR(10),
  ADD COLUMN IF NOT EXISTS agent_name TEXT,
  ADD COLUMN IF NOT EXISTS agent_relationship VARCHAR(100),
  ADD COLUMN IF NOT EXISTS agent_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS agent_phone_alt VARCHAR(30),
  ADD COLUMN IF NOT EXISTS agent_email VARCHAR(200),
  ADD COLUMN IF NOT EXISTS agent_authority TEXT[],
  ADD COLUMN IF NOT EXISTS agent_limitations TEXT,
  ADD COLUMN IF NOT EXISTS psych_med_consent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS hospitalization_consent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS preferred_facility TEXT,
  ADD COLUMN IF NOT EXISTS emergency_intervention_consent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS intervention_notify TEXT,
  ADD COLUMN IF NOT EXISTS intervention_notify_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS therapy_preferences TEXT[],
  ADD COLUMN IF NOT EXISTS therapies_avoid TEXT,
  ADD COLUMN IF NOT EXISTS meds_avoid TEXT,
  ADD COLUMN IF NOT EXISTS non_med_alternatives TEXT[],
  ADD COLUMN IF NOT EXISTS med_notes TEXT,
  ADD COLUMN IF NOT EXISTS comm_preferences TEXT[],
  ADD COLUMN IF NOT EXISTS deescalation_strategies TEXT,
  ADD COLUMN IF NOT EXISTS crisis_avoid TEXT,
  ADD COLUMN IF NOT EXISTS spiritual_care VARCHAR(50),
  ADD COLUMN IF NOT EXISTS faith_tradition TEXT,
  ADD COLUMN IF NOT EXISTS spiritual_practices TEXT,
  ADD COLUMN IF NOT EXISTS chaplain_contact TEXT,
  ADD COLUMN IF NOT EXISTS cultural_mindfulness VARCHAR(50),
  ADD COLUMN IF NOT EXISTS what_matters_most TEXT,
  ADD COLUMN IF NOT EXISTS strengths_and_comforts TEXT,
  ADD COLUMN IF NOT EXISTS end_of_life_instructions VARCHAR(10),
  ADD COLUMN IF NOT EXISTS end_of_life_details TEXT,
  ADD COLUMN IF NOT EXISTS polst_on_file VARCHAR(50),
  ADD COLUMN IF NOT EXISTS resident_name TEXT,
  ADD COLUMN IF NOT EXISTS resident_signature TEXT,
  ADD COLUMN IF NOT EXISTS resident_sign_date DATE,
  ADD COLUMN IF NOT EXISTS witness1_signature TEXT,
  ADD COLUMN IF NOT EXISTS witness1_date DATE,
  ADD COLUMN IF NOT EXISTS witness2_signature TEXT,
  ADD COLUMN IF NOT EXISTS witness2_date DATE,
  ADD COLUMN IF NOT EXISTS agent_ack_name TEXT,
  ADD COLUMN IF NOT EXISTS agent_ack_signature TEXT,
  ADD COLUMN IF NOT EXISTS agent_ack_date DATE,
  ADD COLUMN IF NOT EXISTS staff_sign_name TEXT,
  ADD COLUMN IF NOT EXISTS staff_signature TEXT,
  ADD COLUMN IF NOT EXISTS staff_sign_date DATE,
  ADD COLUMN IF NOT EXISTS step_1_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_2_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_3_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_4_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_5_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS step_6_completed BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS submitted_by UUID REFERENCES ref.staff(id);

-- ---------------------------------------------------------------------------
-- Admission documents + notification linkage used by document endpoints
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS care.admission_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES ref.tenants(id) ON DELETE CASCADE,
  admission_form_id UUID NOT NULL REFERENCES care.pending_admissions(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL CHECK (document_type IN ('nursing', 'pre_screening', 'advance_directive')),
  file_name TEXT NOT NULL,
  file_data BYTEA NOT NULL,
  file_size INTEGER NOT NULL CHECK (file_size > 0 AND file_size <= 52428800),
  mime_type TEXT DEFAULT 'application/pdf',
  created_by UUID NOT NULL REFERENCES ref.staff(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_admission_documents_form_type
  ON care.admission_documents(admission_form_id, document_type)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_admission_documents_tenant_created
  ON care.admission_documents(tenant_id, created_at DESC)
  WHERE deleted_at IS NULL;

ALTER TABLE care.admission_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admission_documents_tenant_isolation ON care.admission_documents;
CREATE POLICY admission_documents_tenant_isolation ON care.admission_documents
  USING (tenant_id = care.current_tenant_id())
  WITH CHECK (tenant_id = care.current_tenant_id());

ALTER TABLE care.notifications
  ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS category VARCHAR(50),
  ADD COLUMN IF NOT EXISTS notification_type TEXT DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS document_id UUID REFERENCES care.admission_documents(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS related_admission_id UUID REFERENCES care.pending_admissions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_notifications_document_id
  ON care.notifications(document_id)
  WHERE dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_related_admission_id
  ON care.notifications(related_admission_id, created_at DESC)
  WHERE dismissed_at IS NULL;

-- Auth/staff/resident-request compatibility for older deployed schemas.
ALTER TABLE care.user_accounts
  ADD COLUMN IF NOT EXISTS failed_attempts SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS password_changed_required BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS username VARCHAR(200);

ALTER TABLE ref.staff
  ADD COLUMN IF NOT EXISTS license_no VARCHAR(50),
  ADD COLUMN IF NOT EXISTS employee_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS shift VARCHAR(50),
  ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(255),
  ADD COLUMN IF NOT EXISTS certifications TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE care.resident_requests
  ADD COLUMN IF NOT EXISTS submitted_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS response TEXT,
  ADD COLUMN IF NOT EXISTS responded_by UUID REFERENCES ref.staff(id),
  ADD COLUMN IF NOT EXISTS responded_at TIMESTAMPTZ;
