const fs = require('fs');

const workQueue = JSON.parse(fs.readFileSync('work-queue.json', 'utf8'));

const newTasks = [
  {
    id: 'QUEUE-STAFF-001',
    team: 'frontend',
    title: 'UI/UX Modernization - Staff Page Design System',
    description: 'Implement modern UI/UX best practices across the staff page. Apply consistent design tokens (spacing, typography, colors), implement accessible component library patterns, ensure responsive design for all screen sizes, add loading states and skeleton screens, implement proper error boundaries with user-friendly messages, standardize form inputs with validation feedback, add tooltips and help text. Audit accessibility (WCAG 2.1 AA), remove all mock/hardcoded data placeholders.',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-002',
    team: 'frontend',
    title: 'Remove Mock Data & Connect Live API Endpoints',
    description: 'Replace all hardcoded mock data with live API calls. Connect all sections (Dashboard, My Residents, Progress Notes, Medications, Incident Report, Drug Disposal, Evacuation Drill) to their respective API endpoints. Implement proper data fetching with useEffect, handle loading/error states gracefully, add pagination for large datasets, implement search/filter functionality, ensure data refresh on mutations.',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-003',
    team: 'backend',
    title: 'Staff API Route Hardening & Missing Endpoints',
    description: 'Audit all staff-facing API routes: add missing endpoints for staff dashboard, residents assignment, progress notes, medications management, incident reporting. Implement consistent pagination (limit, offset). Add proper error responses with actionable messages. Ensure all routes use withTenantClient() for RLS enforcement. Implement rate limiting on sensitive endpoints. Add request validation middleware. Document all endpoints with request/response schemas.',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-004',
    team: 'testing',
    title: 'Test all staff API endpoints for errors and data consistency',
    description: 'Test all staff-related endpoints. Verify correct status codes, proper HIPAA compliance (tenant isolation), data consistency, error handling. Check authentication/authorization on each endpoint. Verify staff can only see their own residents and data.',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-005',
    team: 'frontend',
    title: 'Test all staff section pages for visual bugs and missing data',
    description: 'Navigate through all staff sections: Dashboard, My Residents, Progress Notes, Medications, Incident Report, Drug Disposal, Evacuation Drill. Check for rendering errors, missing data, broken buttons, console errors. Document all issues found.',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-006',
    team: 'testing',
    title: 'Create comprehensive staff page test suite',
    description: 'Write Jest + RTL tests for staff page components: StaffApp, DashboardView, MyResidentsView, ProgressNotesView, etc. Test navigation, state management, API calls, user interactions. Target 75%+ code coverage for staff page.',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-007',
    team: 'backend',
    title: 'Ensure staff API endpoints have proper auth checks',
    description: 'Review src/app/api/v1/ routes used by staff page. Ensure all endpoints check user roles/permissions. Return 401/403 with clear error messages. Ensure staff can only access their own data. Verify RLS policies correctly isolate staff from other tenants\' data.',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-008',
    team: 'database',
    title: 'Schema Verification for Staff-Related Tables',
    description: 'Review staff-related table schemas: ensure all tables have tenant_id column and proper RLS policies. Verify withTenantClient() is correctly setting app.tenant_id. Check encryption column definitions. Add database constraints to prevent NULL tenant_id. Verify indexes on common query paths (tenant_id, staff_id, resident_id).',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-009',
    team: 'testing',
    title: 'E2E Tests - Staff Page Full Workflow',
    description: 'Write comprehensive E2E tests covering: staff login → view dashboard → view assigned residents → create progress note → create incident report → drug disposal log → evacuation drill → view medications. Use real database. Test all CRUD operations. Test error scenarios. Target 80%+ coverage of staff page user flows.',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  },
  {
    id: 'QUEUE-STAFF-010',
    team: 'testing',
    title: 'Unit Tests - Staff API Routes & Permissions',
    description: 'Write unit tests for all staff-facing API routes: test authorization checks pass/fail correctly, test input validation, test error responses, test edge cases. Mock database for speed. Aim for 90%+ code coverage on staff API routes. Test that PERMISSIONS constants are correctly enforced.',
    status: 'pending',
    priority: 'high',
    createdAt: new Date().toISOString(),
    assignedTo: null,
    startedAt: null,
    completedAt: null,
    tokensUsed: 0,
    subtasks: [],
    retryCount: 0,
    lastResetAt: null,
    failureReason: null,
    summary: null,
    filesChanged: [],
    agentUsed: null
  }
];

// Add tasks to pending queue
newTasks.forEach(task => {
  workQueue.queue.push(task);
});

workQueue.stats.totalTasks += newTasks.length;
workQueue.stats.pending += newTasks.length;
workQueue.lastUpdated = new Date().toISOString();

fs.writeFileSync('work-queue.json', JSON.stringify(workQueue, null, 2));
console.log(`✅ Added ${newTasks.length} staff page tasks to work queue`);
console.log(`Total pending tasks: ${workQueue.stats.pending}`);
