export const RESIDENTS = [
  {
    id: "eleanor-whitfield", name: "Eleanor Whitfield", room: "W-104", level: "Assisted living",
    status: "Active", tone: "green", admitted: "Mar 2024", dob: "November 14, 1942",
    primaryContact: "Claire Whitfield · Daughter", contactPhone: "(555) 014-2180",
    carePlan: { reviewed: "June 18, 2026", focus: "Maintain independence with daily routines", nextReview: "September 2026", coordinator: "Amara Koch" },
    medications: [{ name: "Scheduled medications", detail: "3 active · next review Jul 2" }, { name: "As-needed medications", detail: "1 available · no recent use" }],
    notes: [{ title: "Participated in morning activities", meta: "Today · P. Nair" }, { title: "Family visit completed", meta: "Yesterday · Front desk" }],
    incidents: [{ title: "No open incidents", meta: "Last 90 days" }],
    documents: [{ title: "Current care plan", meta: "Reviewed Jun 18, 2026" }, { title: "Resident preferences", meta: "Updated May 30, 2026" }],
  },
  {
    id: "marcus-bell", name: "Marcus Bell", room: "M-210", level: "Memory care",
    status: "Active", tone: "green", admitted: "Jan 2024", dob: "February 3, 1938",
    primaryContact: "David Bell · Son", contactPhone: "(555) 013-7712",
    carePlan: { reviewed: "June 10, 2026", focus: "Support a consistent and familiar daily routine", nextReview: "August 2026", coordinator: "Tomas Reyes" },
    medications: [{ name: "Scheduled medications", detail: "4 active · administration on schedule" }, { name: "Medication review", detail: "Completed Jun 10" }],
    notes: [{ title: "Enjoyed music group", meta: "Today · T. Reyes" }, { title: "Routine maintained throughout shift", meta: "Yesterday · D. Okafor" }],
    incidents: [{ title: "No open incidents", meta: "Last 90 days" }],
    documents: [{ title: "Current care plan", meta: "Reviewed Jun 10, 2026" }, { title: "Family communication plan", meta: "Updated Apr 22, 2026" }],
  },
  {
    id: "rosa-iniguez", name: "Rosa Iniguez", room: "N-118", level: "Skilled nursing",
    status: "Active", tone: "green", admitted: "Nov 2023", dob: "July 28, 1946",
    primaryContact: "Lucia Iniguez · Niece", contactPhone: "(555) 018-4031",
    carePlan: { reviewed: "June 20, 2026", focus: "Support comfort, mobility, and preferred activities", nextReview: "July 2026", coordinator: "Priya Nair" },
    medications: [{ name: "Scheduled medications", detail: "5 active · next review Jul 8" }, { name: "Medication reconciliation", detail: "Completed at last review" }],
    notes: [{ title: "Completed afternoon mobility activity", meta: "Today · P. Nair" }, { title: "Meal preferences reviewed", meta: "Jun 21 · D. Okafor" }],
    incidents: [{ title: "1 incident under follow-up", meta: "Follow-up due Jun 26" }],
    documents: [{ title: "Current care plan", meta: "Reviewed Jun 20, 2026" }, { title: "Mobility support summary", meta: "Updated Jun 12, 2026" }],
  },
  {
    id: "henry-osei", name: "Henry Osei", room: "—", level: "Assisted living",
    status: "Pending", tone: "amber", admitted: "—", dob: "September 9, 1951",
    primaryContact: "Ama Osei · Sister", contactPhone: "(555) 016-8890",
    carePlan: { reviewed: "Not started", focus: "Initial plan to be completed after admission", nextReview: "After admission", coordinator: "Unassigned" },
    medications: [], notes: [{ title: "Admission paperwork awaiting review", meta: "Jun 22 · Admissions" }],
    incidents: [{ title: "No incidents", meta: "Not yet admitted" }],
    documents: [{ title: "Admission intake", meta: "Draft · updated Jun 22, 2026" }],
  },
  {
    id: "grace-tan", name: "Grace Tan", room: "W-106", level: "Assisted living",
    status: "Active", tone: "green", admitted: "Feb 2024", dob: "May 17, 1944",
    primaryContact: "Mei Tan · Daughter", contactPhone: "(555) 019-2024",
    carePlan: { reviewed: "June 4, 2026", focus: "Encourage social connection and independent choices", nextReview: "September 2026", coordinator: "Amara Koch" },
    medications: [{ name: "Scheduled medications", detail: "2 active · administration on schedule" }],
    notes: [{ title: "Attended garden group", meta: "Today · A. Koch" }, { title: "Resident preferences confirmed", meta: "Jun 20 · P. Nair" }],
    incidents: [{ title: "No open incidents", meta: "Last 90 days" }],
    documents: [{ title: "Current care plan", meta: "Reviewed Jun 4, 2026" }, { title: "Activity preferences", meta: "Updated Jun 20, 2026" }],
  },
  {
    id: "albert-nwosu", name: "Albert Nwosu", room: "M-205", level: "Memory care",
    status: "Discharged", tone: "gray", admitted: "Aug 2023", dob: "January 22, 1940",
    primaryContact: "Nneka Nwosu · Daughter", contactPhone: "(555) 011-6022",
    carePlan: { reviewed: "April 16, 2026", focus: "Archived after transition to another community", nextReview: "Not scheduled", coordinator: "Tomas Reyes" },
    medications: [{ name: "Medication summary", detail: "Archived at discharge" }],
    notes: [{ title: "Discharge handoff completed", meta: "May 2 · T. Reyes" }],
    incidents: [{ title: "No open incidents", meta: "Closed at discharge" }],
    documents: [{ title: "Discharge summary", meta: "Finalized May 2, 2026" }, { title: "Archived care plan", meta: "Reviewed Apr 16, 2026" }],
  },
  {
    id: "lillian-park", name: "Lillian Park", room: "N-120", level: "Skilled nursing",
    status: "Active", tone: "green", admitted: "Dec 2023", dob: "March 11, 1936",
    primaryContact: "Daniel Park · Son", contactPhone: "(555) 017-1147",
    carePlan: { reviewed: "June 16, 2026", focus: "Support comfort and participation in preferred routines", nextReview: "August 2026", coordinator: "Priya Nair" },
    medications: [{ name: "Scheduled medications", detail: "4 active · next review Jul 11" }],
    notes: [{ title: "Morning routine completed", meta: "Today · D. Okafor" }, { title: "Joined reading group", meta: "Yesterday · P. Nair" }],
    incidents: [{ title: "No open incidents", meta: "Last 90 days" }],
    documents: [{ title: "Current care plan", meta: "Reviewed Jun 16, 2026" }, { title: "Resident preferences", meta: "Updated May 18, 2026" }],
  },
];

export function getResident(id) {
  return RESIDENTS.find((resident) => resident.id === id);
}
