import { authenticate, authorize, handleError, getRequestContext } from '@/lib/auth-guard.js';
import { withTenantClient } from '@/lib/db.js';
import { PERMISSIONS } from '@/lib/roles.js';
import { AuditLogger } from '@/lib/audit-logger.js';
import { generatePassword } from '@/lib/credential-generator.js';
import { validateUUID } from '@/lib/request-validator.js';
import bcrypt from 'bcryptjs';

const audit = new AuditLogger();

/**
 * POST /api/v1/admin/accounts/[id]/password
 * Reset a user account's password. Admin chooses: type a new password, or
 * generate a secure one. The plaintext is returned in the response body
 * exactly once — the client must show it to the admin and never persist it.
 *
 * Body:
 *   generate?: boolean  — true to auto-generate
 *   password?: string   — required if generate is not true; min length 8
 *   notify?: boolean    — default true; emit an in-app notification w/ creds
 *
 * Response: { email, password, mustChangeOnLogin: true }
 * Requires: ACCOUNTS_MANAGE permission.
 */
export async function POST(request, { params }) {
  try {
    const authResult = await authenticate(request);
    if (authResult.error) {
      return Response.json({ error: authResult.error }, { status: authResult.status });
    }
    const { user } = authResult;

    if (!authorize(user.role, PERMISSIONS.ACCOUNTS_MANAGE)) {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    if (!validateUUID(id)) {
      return Response.json({ error: 'id must be a valid UUID' }, { status: 422 });
    }

    const body = await request.json();
    const { generate, password: rawPassword, notify = true } = body;

    let newPassword;
    if (generate === true) {
      newPassword = generatePassword(14);
    } else {
      if (!rawPassword || typeof rawPassword !== 'string') {
        return Response.json({ error: 'password is required unless generate is true' }, { status: 422 });
      }
      if (rawPassword.length < 8) {
        return Response.json({ error: 'password must be at least 8 characters' }, { status: 422 });
      }
      if (rawPassword.length > 128) {
        return Response.json({ error: 'password must be 128 characters or fewer' }, { status: 422 });
      }
      newPassword = rawPassword;
    }

    const passwordHash = await bcrypt.hash(newPassword, 12);

    const result = await withTenantClient(user.tenantId, user.staffId, async (client) => {
      const { rows } = await client.query(
        `UPDATE care.user_accounts
            SET password_hash      = $1,
                password_changed_required = TRUE,
                failed_attempts    = 0,
                locked_until       = NULL,
                updated_at         = NOW()
          WHERE id = $2 AND tenant_id = $3
          RETURNING id, email, role, staff_id, resident_id`,
        [passwordHash, id, user.tenantId]
      );
      if (!rows.length) throw { status: 404, message: 'Account not found' };
      const account = rows[0];

      // Audit trail (credential_history exists from earlier migration)
      await client.query(
        `INSERT INTO audit_log.credential_history (
           tenant_id, user_account_id, staff_id, resident_id, credential_type,
           username, password_hash, was_temporary, generated_by, reason, generated_at
         ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())`,
        [
          user.tenantId,
          account.id,
          account.staff_id,
          account.resident_id,
          account.staff_id ? 'staff' : 'resident',
          account.email,
          passwordHash,
          true,
          user.staffId,
          generate ? 'Generated by admin (Account Management)' : 'Reset by admin (Account Management)',
        ]
      );

      if (notify) {
        // Visible only to admins/superadmins. Body contains the plaintext —
        // the UI should warn admin this is a one-time view and offer to
        // delete the notification after they record it.
        await client.query(
          `INSERT INTO care.notifications (
             tenant_id, role_filter, type, notification_type, category,
             title, body, action_url, reference_id
           ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
          [
            user.tenantId,
            'admin,superadmin',
            'credentials',
            'new_credentials',
            'account',
            `Password ${generate ? 'generated' : 'reset'} for ${account.email}`,
            JSON.stringify({ email: account.email, password: newPassword, mustChangeOnLogin: true, oneTimeView: true }),
            '/admin?view=account_management',
            account.id,
          ]
        );
      }

      return account;
    });

    await audit.logUpdate({
      tableName: 'care.user_accounts',
      recordId: result.id,
      oldValues: { password_hash: '[REDACTED]' },
      newValues: { password_hash: '[REDACTED]', password_changed_required: true },
      diffKeys: ['password_hash', 'password_changed_required'],
      req: getRequestContext(request, user),
    });
    return Response.json({
      email: result.email,
      password: newPassword,
      generated: generate === true,
      mustChangeOnLogin: true,
      message: 'Show this password to the user now — it will not be shown again.',
    });
  } catch (err) {
    if (err && err.status) {
      return Response.json({ error: err.message }, { status: err.status });
    }
    return handleError(err);
  }
}
