export const MASKED = "Information on file";

export const FACE_SHEET_SECTIONS = [
  {
    id: "identification",
    title: "Resident Identification",
    fields: [
      { key: "legal_name", label: "Resident Legal Name" },
      { key: "preferred_name", label: "Chosen / Preferred Name" },
      { key: "pronouns", label: "Pronouns" },
      { key: "gender_identity", label: "Gender Identity" },
      { key: "date_of_birth", label: "Date of Birth", sensitive: true },
      { key: "age", label: "Age" },
      { key: "marital_status", label: "Marital Status" },
      { key: "religious_preference", label: "Religious Preference" },
      { key: "ssn", label: "Social Security #", sensitive: true },
      { key: "resident_id", label: "Resident ID #" },
      { key: "previous_address", label: "Previous Address", sensitive: true, wide: true },
      { key: "date_of_admission", label: "Date of Admission" },
      { key: "admitted_from", label: "Admitted From" },
    ],
  },
  {
    id: "legal_status",
    title: "Legal Status & Capability",
    fields: [
      { key: "legal_status", label: "Legal Status" },
      { key: "capability", label: "Capability" },
      { key: "advance_directive_status", label: "Advance Directive Status" },
      { key: "polst_dnr", label: "POLST / DNR on File" },
      { key: "polst_dnr_date", label: "Date Signed", sensitive: true },
      { key: "evacuation_capability", label: "Evacuation Capability" },
      { key: "mobility_aids", label: "Mobility Aids / Notes", wide: true },
    ],
  },
  {
    id: "insurance",
    title: "Insurance Information",
    fields: [
      { key: "primary_insurance", label: "Primary Insurance" },
      { key: "primary_policy_id", label: "Policy / ID #", sensitive: true },
      { key: "primary_group", label: "Group #", sensitive: true },
      { key: "primary_effective_date", label: "Effective Date", sensitive: true },
      { key: "secondary_insurance", label: "Secondary Insurance" },
      { key: "secondary_policy_id", label: "Policy / ID #", sensitive: true },
      { key: "medicare_number", label: "Medicare #", sensitive: true },
      { key: "medicaid_number", label: "Medicaid #", sensitive: true },
      { key: "insurance_phone", label: "Insurance Phone", sensitive: true },
      { key: "subscriber", label: "Subscriber" },
    ],
  },
  {
    id: "diagnoses_allergies",
    title: "Diagnoses & Allergies",
    fields: [
      { key: "dsm_primary", label: "DSM Diagnosis (Primary)" },
      { key: "dsm_secondary", label: "DSM Diagnosis (Secondary)" },
      { key: "additional_behavioral_dx", label: "Additional Behavioral Health Dx", wide: true },
      { key: "physical_dx", label: "Physical Health Diagnosis", wide: true },
      { key: "additional_medical", label: "Additional Medical Conditions", wide: true },
      { key: "allergies_medication", label: "Allergies (Medication)", wide: true },
      { key: "allergies_food_env", label: "Allergies (Food / Environmental)", wide: true },
      { key: "allergy_severity", label: "Allergy Reaction / Severity", wide: true },
    ],
  },
  {
    id: "providers",
    title: "Medical & Behavioral Health Providers",
    fields: [
      { key: "pcp_name", label: "Primary Care Physician (PCP)" },
      { key: "pcp_clinic", label: "PCP Clinic / Address", sensitive: true },
      { key: "pcp_phone", label: "PCP Phone", sensitive: true },
      { key: "psychiatrist_name", label: "Psychiatrist" },
      { key: "psychiatrist_clinic", label: "Psychiatrist Clinic / Address", sensitive: true },
      { key: "psychiatrist_phone", label: "Psychiatrist Phone", sensitive: true },
      { key: "therapist_name", label: "Therapist / Counselor" },
      { key: "therapist_phone", label: "Therapist Phone", sensitive: true },
      { key: "dentist_name", label: "Dentist" },
      { key: "dentist_phone", label: "Dentist Phone", sensitive: true },
      { key: "specialist_type", label: "Specialist (Type)" },
      { key: "specialist_name", label: "Specialist Name" },
      { key: "specialist_phone", label: "Specialist Phone", sensitive: true },
      { key: "specialist_address", label: "Specialist Address", sensitive: true },
      { key: "additional_specialist", label: "Additional Specialist", wide: true },
    ],
  },
  {
    id: "pharmacy",
    title: "Pharmacy Information",
    fields: [
      { key: "preferred_pharmacy", label: "Preferred Pharmacy" },
      { key: "pharmacy_address", label: "Pharmacy Address", sensitive: true },
      { key: "pharmacy_phone", label: "Pharmacy Phone", sensitive: true },
      { key: "pharmacy_fax", label: "Pharmacy Fax", sensitive: true },
      { key: "backup_pharmacy", label: "After-Hours / Backup Pharmacy" },
    ],
  },
  {
    id: "emergency_contacts",
    title: "Emergency Contacts",
    fields: [
      { key: "primary_name", label: "Primary Emergency Contact" },
      { key: "primary_relationship", label: "Relationship" },
      { key: "primary_phone_home", label: "Phone (Home)", sensitive: true },
      { key: "primary_phone_cell", label: "Phone (Cell)", sensitive: true },
      { key: "primary_address", label: "Address", sensitive: true, wide: true },
      { key: "primary_email", label: "Email", sensitive: true },
      { key: "secondary_name", label: "Secondary Emergency Contact" },
      { key: "secondary_relationship", label: "Relationship" },
      { key: "secondary_phone", label: "Phone", sensitive: true },
      { key: "secondary_email", label: "Email", sensitive: true },
    ],
  },
  {
    id: "legal_reps",
    title: "Legal Representatives, Guardian & Family",
    fields: [
      { key: "legal_rep_name", label: "Legal Representative" },
      { key: "legal_rep_authority", label: "Type / Authority" },
      { key: "legal_rep_phone", label: "Legal Rep Phone", sensitive: true },
      { key: "legal_rep_email", label: "Legal Rep Email", sensitive: true },
      { key: "legal_rep_address", label: "Legal Rep Address", sensitive: true, wide: true },
      { key: "guardian_name", label: "Guardian" },
      { key: "guardian_phone", label: "Guardian Phone", sensitive: true },
      { key: "guardian_address", label: "Guardian Address", sensitive: true, wide: true },
      { key: "conservator_name", label: "Conservator" },
      { key: "conservator_phone", label: "Conservator Phone", sensitive: true },
      { key: "conservator_address", label: "Conservator Address", sensitive: true, wide: true },
      { key: "nok_name", label: "Parent(s) / Next of Kin" },
      { key: "nok_relationship", label: "Relationship" },
      { key: "nok_phone", label: "Parent / NOK Phone", sensitive: true },
      { key: "nok_email", label: "Parent / NOK Email", sensitive: true },
      { key: "nok_address", label: "Parent / NOK Address", sensitive: true, wide: true },
    ],
  },
  {
    id: "service_coordination",
    title: "Service Coordination",
    fields: [
      { key: "case_manager", label: "Case Manager" },
      { key: "agency", label: "Agency" },
      { key: "case_manager_phone", label: "Case Manager Phone", sensitive: true },
      { key: "case_manager_email", label: "Case Manager Email", sensitive: true },
      { key: "therapist_primary", label: "Therapist (Primary)" },
      { key: "therapist_contact", label: "Phone / Email", sensitive: true },
      { key: "additional_therapist", label: "Additional Therapist / Modality" },
      { key: "day_program", label: "Day Program" },
      { key: "day_program_phone", label: "Day Program Phone", sensitive: true },
      { key: "day_program_address", label: "Day Program Address", sensitive: true, wide: true },
      { key: "day_program_schedule", label: "Day Program Schedule" },
      { key: "transportation_provider", label: "Transportation Provider" },
      { key: "transportation_phone", label: "Transportation Phone", sensitive: true },
    ],
  },
  {
    id: "signatures",
    title: "Signatures",
    fields: [
      { key: "form_completed_date", label: "Date Form Completed" },
      { key: "form_updated_date", label: "Form Updated" },
      { key: "resident_signature", label: "Resident / Representative Signature", sensitive: true },
      { key: "resident_signature_date", label: "Signature Date", sensitive: true },
      { key: "staff_name_title", label: "Staff Completing Form (Print Name & Title)" },
      { key: "staff_signature_date", label: "Staff Date" },
    ],
  },
];

function buildFaceSheet({
  name,
  preferredName,
  gender,
  room,
  careLevel,
  dob,
  admitted,
  legalStatus = "Voluntary",
  capability = "Capable",
  advanceDirective = "On File",
  dnr = "Yes",
  evacuation,
  mobility,
  primaryDiagnosis,
  secondaryDiagnosis,
  behavioral,
  physical,
  medical,
  allergies,
  allergySeverity,
  pcp,
  psychiatrist,
  therapist,
  dentist = "Dental provider on file",
  pharmacy = "Preferred pharmacy on file",
  primaryContact,
  emergencyContact,
  legalRep,
  caseManager,
  agency = "Colaris Care coordination",
  dayProgram = "Activities program",
  transportation = "Facility transportation",
  staff,
  completed,
  updated,
}) {
  return {
    legal_name: name,
    preferred_name: preferredName || "—",
    pronouns: "Information on file",
    gender_identity: gender,
    date_of_birth: MASKED,
    age: "Information on file",
    marital_status: "Information on file",
    religious_preference: "Information on file",
    ssn: MASKED,
    resident_id: MASKED,
    previous_address: MASKED,
    date_of_admission: admitted,
    admitted_from: "Information on file",
    legal_status: legalStatus,
    capability,
    advance_directive_status: advanceDirective,
    polst_dnr: dnr,
    polst_dnr_date: MASKED,
    evacuation_capability: evacuation,
    mobility_aids: mobility,
    primary_insurance: "Insurance on file",
    primary_policy_id: MASKED,
    primary_group: MASKED,
    primary_effective_date: MASKED,
    secondary_insurance: "Information on file",
    secondary_policy_id: MASKED,
    medicare_number: MASKED,
    medicaid_number: MASKED,
    insurance_phone: MASKED,
    subscriber: "Information on file",
    dsm_primary: primaryDiagnosis,
    dsm_secondary: secondaryDiagnosis,
    additional_behavioral_dx: behavioral,
    physical_dx: physical,
    additional_medical: medical,
    allergies_medication: allergies,
    allergies_food_env: "Information on file",
    allergy_severity: allergySeverity,
    pcp_name: pcp,
    pcp_clinic: MASKED,
    pcp_phone: MASKED,
    psychiatrist_name: psychiatrist,
    psychiatrist_clinic: MASKED,
    psychiatrist_phone: MASKED,
    therapist_name: therapist,
    therapist_phone: MASKED,
    dentist_name: dentist,
    dentist_phone: MASKED,
    specialist_type: "Information on file",
    specialist_name: "Information on file",
    specialist_phone: MASKED,
    specialist_address: MASKED,
    additional_specialist: "See provider records on file.",
    preferred_pharmacy: pharmacy,
    pharmacy_address: MASKED,
    pharmacy_phone: MASKED,
    pharmacy_fax: MASKED,
    backup_pharmacy: "After-hours pharmacy on file",
    primary_name: primaryContact.name,
    primary_relationship: primaryContact.relationship,
    primary_phone_home: MASKED,
    primary_phone_cell: MASKED,
    primary_address: MASKED,
    primary_email: MASKED,
    secondary_name: emergencyContact.name,
    secondary_relationship: emergencyContact.relationship,
    secondary_phone: MASKED,
    secondary_email: MASKED,
    legal_rep_name: legalRep || primaryContact.name,
    legal_rep_authority: "Information on file",
    legal_rep_phone: MASKED,
    legal_rep_email: MASKED,
    legal_rep_address: MASKED,
    guardian_name: "Information on file",
    guardian_phone: MASKED,
    guardian_address: MASKED,
    conservator_name: "Information on file",
    conservator_phone: MASKED,
    conservator_address: MASKED,
    nok_name: emergencyContact.name,
    nok_relationship: emergencyContact.relationship,
    nok_phone: MASKED,
    nok_email: MASKED,
    nok_address: MASKED,
    case_manager: caseManager,
    agency,
    case_manager_phone: MASKED,
    case_manager_email: MASKED,
    therapist_primary: therapist,
    therapist_contact: MASKED,
    additional_therapist: "Information on file",
    day_program: dayProgram,
    day_program_phone: MASKED,
    day_program_address: MASKED,
    day_program_schedule: "Information on file",
    transportation_provider: transportation,
    transportation_phone: MASKED,
    form_completed_date: completed,
    form_updated_date: updated,
    resident_signature: MASKED,
    resident_signature_date: MASKED,
    staff_name_title: staff,
    staff_signature_date: updated,
    raw_dob: dob,
  };
}

export const FACE_SHEETS = [
  {
    id: "eleanor-whitfield",
    name: "Eleanor Whitfield",
    room: "W-104",
    careLevel: "Assisted living",
    dob: "November 14, 1942",
    sex: "Female",
    status: "Current",
    tone: "green",
    lastUpdated: "June 18, 2026",
    admitted: "March 12, 2024",
    lastReviewed: "June 18, 2026",
    primaryContact: { name: "Claire Whitfield", relationship: "Daughter", phone: MASKED },
    emergencyContact: { name: "Jon Whitfield", relationship: "Son", phone: MASKED },
    physician: { name: "Dr. Maya Patel", phone: MASKED },
    careManager: { name: "Amara Koch", phone: MASKED },
    allergies: { present: true, note: "Seasonal pollen allergy noted" },
    codeStatus: "Full code",
    diet: "Regular diet; prefers low sodium choices",
    mobility: "Independent with a rolling walker",
    insuranceOnFile: true,
    wing: "West wing",
    supportLevel: "Morning routine assistance",
    preferredActivity: "Garden group",
    communication: "Offer choices and allow time to respond",
    emergencyPlan: "Emergency readiness plan on file with facility team",
    faceSheet: buildFaceSheet({
      name: "Eleanor Whitfield",
      preferredName: "Eleanor",
      gender: "Female",
      room: "W-104",
      careLevel: "Assisted living",
      dob: "November 14, 1942",
      admitted: "March 12, 2024",
      evacuation: "Requires Assistance",
      mobility: "Independent with a rolling walker",
      primaryDiagnosis: "Hypertension",
      secondaryDiagnosis: "Osteoarthritis",
      behavioral: "No acute behavioral concerns documented.",
      physical: "Mobility support and blood pressure monitoring.",
      medical: "Seasonal allergy precautions.",
      allergies: "No medication allergy documented.",
      allergySeverity: "Seasonal pollen allergy noted.",
      pcp: "Dr. Maya Patel",
      psychiatrist: "Behavioral health provider on file",
      therapist: "Therapy provider on file",
      primaryContact: { name: "Claire Whitfield", relationship: "Daughter" },
      emergencyContact: { name: "Jon Whitfield", relationship: "Son" },
      caseManager: "Amara Koch",
      legalRep: "Claire Whitfield",
      staff: "Amara Koch, Administrator",
      completed: "June 18, 2026",
      updated: "June 18, 2026",
    }),
  },
  {
    id: "marcus-bell",
    name: "Marcus Bell",
    room: "M-210",
    careLevel: "Memory care",
    dob: "February 3, 1938",
    sex: "Male",
    status: "Current",
    tone: "green",
    lastUpdated: "June 10, 2026",
    admitted: "January 8, 2024",
    lastReviewed: "June 10, 2026",
    primaryContact: { name: "David Bell", relationship: "Son", phone: MASKED },
    emergencyContact: { name: "Nora Bell", relationship: "Daughter", phone: MASKED },
    physician: { name: "Dr. Samuel Reed", phone: MASKED },
    careManager: { name: "Tomas Reyes", phone: MASKED },
    allergies: { present: false, note: "No known allergies reported" },
    codeStatus: "DNR on file",
    diet: "Regular texture; supervised dining",
    mobility: "Standby assistance for longer distances",
    insuranceOnFile: true,
    wing: "Memory care",
    supportLevel: "Consistent routine prompts",
    preferredActivity: "Music group",
    communication: "Use calm, short prompts",
    emergencyPlan: "Emergency readiness plan on file with facility team",
    faceSheet: buildFaceSheet({
      name: "Marcus Bell",
      preferredName: "Marcus",
      gender: "Male",
      room: "M-210",
      careLevel: "Memory care",
      dob: "February 3, 1938",
      admitted: "January 8, 2024",
      legalStatus: "Voluntary",
      capability: "Limited Capability",
      evacuation: "Requires Assistance",
      mobility: "Standby assistance for longer distances",
      primaryDiagnosis: "Major neurocognitive disorder",
      secondaryDiagnosis: "Hypertension",
      behavioral: "Wandering risk; responds well to calm redirection.",
      physical: "Supervised dining and mobility checks.",
      medical: "Routine medication and hydration monitoring.",
      allergies: "No known medication allergies reported.",
      allergySeverity: "No known allergies reported.",
      pcp: "Dr. Samuel Reed",
      psychiatrist: "Behavioral health provider on file",
      therapist: "Therapy provider on file",
      primaryContact: { name: "David Bell", relationship: "Son" },
      emergencyContact: { name: "Nora Bell", relationship: "Daughter" },
      caseManager: "Tomas Reyes",
      legalRep: "David Bell",
      staff: "Tomas Reyes, Care Manager",
      completed: "June 10, 2026",
      updated: "June 10, 2026",
    }),
  },
  {
    id: "rosa-iniguez",
    name: "Rosa Iniguez",
    room: "N-118",
    careLevel: "Skilled nursing",
    dob: "July 28, 1946",
    sex: "Female",
    status: "Review due",
    tone: "amber",
    lastUpdated: "May 2, 2026",
    admitted: "November 19, 2023",
    lastReviewed: "May 2, 2026",
    primaryContact: { name: "Lucia Iniguez", relationship: "Niece", phone: MASKED },
    emergencyContact: { name: "Mateo Iniguez", relationship: "Nephew", phone: MASKED },
    physician: { name: "Dr. Helen Brooks", phone: MASKED },
    careManager: { name: "Priya Nair", phone: MASKED },
    allergies: { present: true, note: "Food allergy noted; see current care plan" },
    codeStatus: "DNR on file",
    diet: "Soft texture; hydration reminders",
    mobility: "One-person assist for transfers",
    insuranceOnFile: true,
    wing: "North wing",
    supportLevel: "Scheduled activity assistance",
    preferredActivity: "Reading group",
    communication: "Confirm preferences before assistance",
    emergencyPlan: "Emergency readiness plan on file with facility team",
    faceSheet: buildFaceSheet({
      name: "Rosa Iniguez",
      preferredName: "Rosa",
      gender: "Female",
      room: "N-118",
      careLevel: "Skilled nursing",
      dob: "July 28, 1946",
      admitted: "November 19, 2023",
      legalStatus: "Voluntary",
      capability: "Limited Capability",
      evacuation: "Total Assist",
      mobility: "One-person assist for transfers",
      primaryDiagnosis: "COPD",
      secondaryDiagnosis: "Diabetes mellitus",
      behavioral: "Fall risk emphasized for daily operations.",
      physical: "Transfer assistance and hydration reminders.",
      medical: "Diabetes and respiratory monitoring.",
      allergies: "Medication allergy documented; verify current chart.",
      allergySeverity: "Severity information on file.",
      pcp: "Dr. Helen Brooks",
      psychiatrist: "Behavioral health provider on file",
      therapist: "Therapy provider on file",
      primaryContact: { name: "Lucia Iniguez", relationship: "Niece" },
      emergencyContact: { name: "Mateo Iniguez", relationship: "Nephew" },
      caseManager: "Priya Nair",
      legalRep: "Lucia Iniguez",
      staff: "Priya Nair, Care Manager",
      completed: "May 2, 2026",
      updated: "May 2, 2026",
    }),
  },
  {
    id: "grace-tan",
    name: "Grace Tan",
    room: "W-106",
    careLevel: "Assisted living",
    dob: "May 17, 1944",
    sex: "Female",
    status: "Current",
    tone: "green",
    lastUpdated: "June 4, 2026",
    admitted: "February 20, 2024",
    lastReviewed: "June 4, 2026",
    primaryContact: { name: "Mei Tan", relationship: "Daughter", phone: MASKED },
    emergencyContact: { name: "Andrew Tan", relationship: "Son", phone: MASKED },
    physician: { name: "Dr. Maya Patel", phone: MASKED },
    careManager: { name: "Amara Koch", phone: MASKED },
    allergies: { present: false, note: "No known allergies reported" },
    codeStatus: "Full code",
    diet: "Vegetarian preference",
    mobility: "Independent",
    insuranceOnFile: true,
    wing: "West wing",
    supportLevel: "Independent daily routine",
    preferredActivity: "Cooking group",
    communication: "Verbal communication; prefers direct explanations",
    emergencyPlan: "Emergency readiness plan on file with facility team",
    faceSheet: buildFaceSheet({
      name: "Grace Tan",
      preferredName: "Grace",
      gender: "Female",
      room: "W-106",
      careLevel: "Assisted living",
      dob: "May 17, 1944",
      admitted: "February 20, 2024",
      evacuation: "Independent",
      mobility: "Independent",
      primaryDiagnosis: "Hypertension",
      secondaryDiagnosis: "None documented",
      behavioral: "No acute behavioral concerns documented.",
      physical: "Independent mobility with routine wellness checks.",
      medical: "Vegetarian dietary preference.",
      allergies: "No known medication allergies reported.",
      allergySeverity: "No known allergies reported.",
      pcp: "Dr. Maya Patel",
      psychiatrist: "Behavioral health provider on file",
      therapist: "Therapy provider on file",
      primaryContact: { name: "Mei Tan", relationship: "Daughter" },
      emergencyContact: { name: "Andrew Tan", relationship: "Son" },
      caseManager: "Amara Koch",
      legalRep: "Mei Tan",
      staff: "Amara Koch, Administrator",
      completed: "June 4, 2026",
      updated: "June 4, 2026",
    }),
  },
  {
    id: "lillian-park",
    name: "Lillian Park",
    room: "N-120",
    careLevel: "Skilled nursing",
    dob: "March 11, 1936",
    sex: "Female",
    status: "Review due",
    tone: "amber",
    lastUpdated: "April 29, 2026",
    admitted: "December 4, 2023",
    lastReviewed: "April 29, 2026",
    primaryContact: { name: "Daniel Park", relationship: "Son", phone: MASKED },
    emergencyContact: { name: "Hannah Park", relationship: "Granddaughter", phone: MASKED },
    physician: { name: "Dr. Helen Brooks", phone: MASKED },
    careManager: { name: "Priya Nair", phone: MASKED },
    allergies: { present: true, note: "Medication allergy documented; verify current chart" },
    codeStatus: "Limited interventions",
    diet: "Easy-to-chew texture",
    mobility: "Wheelchair for distance; assisted transfers",
    insuranceOnFile: true,
    wing: "North wing",
    supportLevel: "Transfer and texture assistance",
    preferredActivity: "Craft circle",
    communication: "Use clear step-by-step explanations",
    emergencyPlan: "Emergency readiness plan on file with facility team",
    faceSheet: buildFaceSheet({
      name: "Lillian Park",
      preferredName: "Lillian",
      gender: "Female",
      room: "N-120",
      careLevel: "Skilled nursing",
      dob: "March 11, 1936",
      admitted: "December 4, 2023",
      legalStatus: "Voluntary",
      capability: "Limited Capability",
      advanceDirective: "On File",
      dnr: "Yes",
      evacuation: "Requires Assistance",
      mobility: "Wheelchair for distance; assisted transfers",
      primaryDiagnosis: "Post-stroke mobility impairment",
      secondaryDiagnosis: "Chronic pain",
      behavioral: "Fall risk; requires transfer cueing.",
      physical: "Easy-to-chew texture and assisted transfers.",
      medical: "Medication allergy documented; verify current chart.",
      allergies: "Medication allergy documented.",
      allergySeverity: "Severity information on file.",
      pcp: "Dr. Helen Brooks",
      psychiatrist: "Behavioral health provider on file",
      therapist: "Therapy provider on file",
      primaryContact: { name: "Daniel Park", relationship: "Son" },
      emergencyContact: { name: "Hannah Park", relationship: "Granddaughter" },
      caseManager: "Priya Nair",
      legalRep: "Daniel Park",
      staff: "Priya Nair, Care Manager",
      completed: "April 29, 2026",
      updated: "April 29, 2026",
    }),
  },
];

export function getFaceSheet(id) {
  return FACE_SHEETS.find((sheet) => sheet.id === id);
}
