export const MASKED = "Information on file";

export const FACE_SHEET_SECTIONS = [
  {
    id: "identification",
    title: "Resident Identification",
    fields: [
      { key: "legal_name", label: "Resident Legal Name" },
      { key: "preferred_name", label: "Chosen / Preferred Name" },
      { key: "pronouns", label: "Pronouns" },
      { key: "gender_identity", label: "Gender Identity" },
      { key: "date_of_birth", label: "Date of Birth", sensitive: true },
      { key: "age", label: "Age" },
      { key: "marital_status", label: "Marital Status" },
      { key: "religious_preference", label: "Religious Preference" },
      { key: "ssn", label: "Social Security #", sensitive: true },
      { key: "resident_id", label: "Resident ID #" },
      { key: "previous_address", label: "Previous Address", sensitive: true, wide: true },
      { key: "date_of_admission", label: "Date of Admission" },
      { key: "admitted_from", label: "Admitted From" },
    ],
  },
  {
    id: "legal_status",
    title: "Legal Status & Capability",
    fields: [
      { key: "legal_status", label: "Legal Status" },
      { key: "capability", label: "Capability" },
      { key: "advance_directive_status", label: "Advance Directive Status" },
      { key: "polst_dnr", label: "POLST / DNR on File" },
      { key: "polst_dnr_date", label: "Date Signed", sensitive: true },
      { key: "evacuation_capability", label: "Evacuation Capability" },
      { key: "mobility_aids", label: "Mobility Aids / Notes", wide: true },
    ],
  },
  {
    id: "insurance",
    title: "Insurance Information",
    fields: [
      { key: "primary_insurance", label: "Primary Insurance" },
      { key: "primary_policy_id", label: "Policy / ID #", sensitive: true },
      { key: "primary_group", label: "Group #", sensitive: true },
      { key: "primary_effective_date", label: "Effective Date", sensitive: true },
      { key: "secondary_insurance", label: "Secondary Insurance" },
      { key: "secondary_policy_id", label: "Policy / ID #", sensitive: true },
      { key: "medicare_number", label: "Medicare #", sensitive: true },
      { key: "medicaid_number", label: "Medicaid #", sensitive: true },
      { key: "insurance_phone", label: "Insurance Phone", sensitive: true },
      { key: "subscriber", label: "Subscriber" },
    ],
  },
  {
    id: "diagnoses_allergies",
    title: "Diagnoses & Allergies",
    fields: [
      { key: "dsm_primary", label: "DSM Diagnosis (Primary)" },
      { key: "dsm_secondary", label: "DSM Diagnosis (Secondary)" },
      { key: "additional_behavioral_dx", label: "Additional Behavioral Health Dx", wide: true },
      { key: "physical_dx", label: "Physical Health Diagnosis", wide: true },
      { key: "additional_medical", label: "Additional Medical Conditions", wide: true },
      { key: "allergies_medication", label: "Allergies (Medication)", wide: true },
      { key: "allergies_food_env", label: "Allergies (Food / Environmental)", wide: true },
      { key: "allergy_severity", label: "Allergy Reaction / Severity", wide: true },
    ],
  },
  {
    id: "providers",
    title: "Medical & Behavioral Health Providers",
    fields: [
      { key: "pcp_name", label: "Primary Care Physician (PCP)" },
      { key: "pcp_clinic", label: "PCP Clinic / Address", sensitive: true },
      { key: "pcp_phone", label: "PCP Phone", sensitive: true },
      { key: "psychiatrist_name", label: "Psychiatrist" },
      { key: "psychiatrist_clinic", label: "Psychiatrist Clinic / Address", sensitive: true },
      { key: "psychiatrist_phone", label: "Psychiatrist Phone", sensitive: true },
      { key: "therapist_name", label: "Therapist / Counselor" },
      { key: "therapist_phone", label: "Therapist Phone", sensitive: true },
      { key: "dentist_name", label: "Dentist" },
      { key: "dentist_phone", label: "Dentist Phone", sensitive: true },
      { key: "specialist_type", label: "Specialist (Type)" },
      { key: "specialist_name", label: "Specialist Name" },
      { key: "specialist_phone", label: "Specialist Phone", sensitive: true },
      { key: "specialist_address", label: "Specialist Address", sensitive: true },
      { key: "additional_specialist", label: "Additional Specialist", wide: true },
    ],
  },
  {
    id: "pharmacy",
    title: "Pharmacy Information",
    fields: [
      { key: "preferred_pharmacy", label: "Preferred Pharmacy" },
      { key: "pharmacy_address", label: "Pharmacy Address", sensitive: true },
      { key: "pharmacy_phone", label: "Pharmacy Phone", sensitive: true },
      { key: "pharmacy_fax", label: "Pharmacy Fax", sensitive: true },
      { key: "backup_pharmacy", label: "After-Hours / Backup Pharmacy" },
    ],
  },
  {
    id: "emergency_contacts",
    title: "Emergency Contacts",
    fields: [
      { key: "primary_name", label: "Primary Emergency Contact" },
      { key: "primary_relationship", label: "Relationship" },
      { key: "primary_phone_home", label: "Phone (Home)", sensitive: true },
      { key: "primary_phone_cell", label: "Phone (Cell)", sensitive: true },
      { key: "primary_address", label: "Address", sensitive: true, wide: true },
      { key: "primary_email", label: "Email", sensitive: true },
      { key: "secondary_name", label: "Secondary Emergency Contact" },
      { key: "secondary_relationship", label: "Relationship" },
      { key: "secondary_phone", label: "Phone", sensitive: true },
      { key: "secondary_email", label: "Email", sensitive: true },
    ],
  },
  {
    id: "legal_reps",
    title: "Legal Representatives, Guardian & Family",
    fields: [
      { key: "legal_rep_name", label: "Legal Representative" },
      { key: "legal_rep_authority", label: "Type / Authority" },
      { key: "legal_rep_phone", label: "Legal Rep Phone", sensitive: true },
      { key: "legal_rep_email", label: "Legal Rep Email", sensitive: true },
      { key: "legal_rep_address", label: "Legal Rep Address", sensitive: true, wide: true },
      { key: "guardian_name", label: "Guardian" },
      { key: "guardian_phone", label: "Guardian Phone", sensitive: true },
      { key: "guardian_address", label: "Guardian Address", sensitive: true, wide: true },
      { key: "conservator_name", label: "Conservator" },
      { key: "conservator_phone", label: "Conservator Phone", sensitive: true },
      { key: "conservator_address", label: "Conservator Address", sensitive: true, wide: true },
      { key: "nok_name", label: "Parent(s) / Next of Kin" },
      { key: "nok_relationship", label: "Relationship" },
      { key: "nok_phone", label: "Parent / NOK Phone", sensitive: true },
      { key: "nok_email", label: "Parent / NOK Email", sensitive: true },
      { key: "nok_address", label: "Parent / NOK Address", sensitive: true, wide: true },
    ],
  },
  {
    id: "service_coordination",
    title: "Service Coordination",
    fields: [
      { key: "case_manager", label: "Case Manager" },
      { key: "agency", label: "Agency" },
      { key: "case_manager_phone", label: "Case Manager Phone", sensitive: true },
      { key: "case_manager_email", label: "Case Manager Email", sensitive: true },
      { key: "therapist_primary", label: "Therapist (Primary)" },
      { key: "therapist_contact", label: "Phone / Email", sensitive: true },
      { key: "additional_therapist", label: "Additional Therapist / Modality" },
      { key: "day_program", label: "Day Program" },
      { key: "day_program_phone", label: "Day Program Phone", sensitive: true },
      { key: "day_program_address", label: "Day Program Address", sensitive: true, wide: true },
      { key: "day_program_schedule", label: "Day Program Schedule" },
      { key: "transportation_provider", label: "Transportation Provider" },
      { key: "transportation_phone", label: "Transportation Phone", sensitive: true },
    ],
  },
  {
    id: "signatures",
    title: "Signatures",
    fields: [
      { key: "form_completed_date", label: "Date Form Completed" },
      { key: "form_updated_date", label: "Form Updated" },
      { key: "resident_signature", label: "Resident / Representative Signature", sensitive: true },
      { key: "resident_signature_date", label: "Signature Date", sensitive: true },
      { key: "staff_name_title", label: "Staff Completing Form (Print Name & Title)" },
      { key: "staff_signature_date", label: "Staff Date" },
    ],
  },
];

export const FACE_SHEETS = [];

export function getFaceSheet(id) {
  return FACE_SHEETS.find((sheet) => sheet.id === id);
}
